### ISSUE TITLE
Low price swicht on disappeared?

### ISSUE THREAD

**Issue by realrelook** [quadpunk/ShellyTibberScript#3]
Hello, I not find in the new code for the shelly the low price trigger anymore.? Has this feature been deleted? 
To be more clear, I miss the price level when the switch should work. This line:
  maxEnergyPrice: 0.65, // Pris över vilket strömmen ska stängas av i lokal valuta för ditt API (Sverige=SEK)

**Comment by quadpunk** [comment]
Thanks for the input, I've not been maintaining this for a while and it's
been modified by sn0w3y, I haven't had time to review it. But if you want
to find the old version you speak about it's available on
https://github.com/quadpunk/ShellyTibberScript/commit/ec6012756bcc3d78db530a2efac87d64e4667ae7

Thanks!

Den mån 6 maj 2024 00:13realrelook ***@***.***> skrev:
