### ISSUE TITLE
Error code: 1006

### ISSUE THREAD

**Issue by realrelook** [quadpunk/ShellyTibberScript#5]
Hi, since a view days I get in the shelly app durning changing the script following message:
WebSocket is closed to 192.168.111.22 Error code: 1006

and the script is not working right now.
Any Idea how to fix this issue.?
Thank you

**Comment by quadpunk** [comment]
No sorry, i havent had time to check up on it. I've backed the verison down to older verison which was previously working, hopefully this works until i can update the newer one.

**Comment by realrelook** [comment]
I did play arround a little, and it looks like that this error is only existing in the Shelly APP. The Script (old original) is working as long as you do not get the error msg in the APP. If so, you need to start the Script and / or klick the green arrow in the script output area to make it run again.

**Comment by realrelook** [comment]
With the answer above this issue is closed.
